image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

  TEST_IMAGE: registry.gitlab.com/mycro/mycro/tests

stages:
  - test

unit_test_backend:
  stage: test
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

    # need to support branches with / in the their name. Do this by replacing / with -
    - TAG=$(echo $CI_COMMIT_REF_NAME | sed "s/\//-/g")
    - IMAGE_WITH_TAG=$TEST_IMAGE:$TAG

    - docker pull $IMAGE_WITH_TAG || docker pull $TEST_IMAGE:latest || true
    - docker build --cache-from $IMAGE_WITH_TAG --cache-from $TEST_IMAGE:latest -t $IMAGE_WITH_TAG -t $TEST_IMAGE:latest -f server.Dockerfile .
    - docker push $IMAGE_WITH_TAG # push this first so we don't have to rebuild if tests fail
    - docker run $IMAGE_WITH_TAG python manage.py test -v 2
    - docker push $TEST_IMAGE:latest
