jobs:
  include:
    - stage: unit test
      language: node_js
      node_js: "10.4"
      cache:
        directories:
        - frontend/node_modules
      before_install:
        - cd frontend
      install:
        - npm install
      script:
        - npm run prettier-check
    - stage: unit test
      language: python
      python:
        - "3.6"
      dist: xenial
      services:
        - postgresql
      addons:
        postgresql: "9.6"
      before_install:
        # TODO this can probably be converted to using the addons feature of CI
        - sudo apt-get install -yq --no-install-recommends --no-install-suggests automake build-essential libffi-dev libgmp-dev libssl-dev libtool pkg-config python3-dev python3-pip software-properties-common
        - cd backend
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres

        # the ethereum ppa only has solc v5 and higher.
        # install a lower version using the py-solc package
        - python3 -m solc.install v0.4.24
        - ln -s /home/travis/.py-solc/solc-v0.4.24/bin/solc ~/bin/solc
      script:
        - cd ..
        - python manage.py test -v 2
