version: '2'

services:
  parity:
    image: parity/parity:v1.11.7
    command: --light --chain ropsten --base-path /root/.local/share/io.parity.ethereum --unsafe-expose
    ports:
      - "8545:8545"
      - "8180:8180"
#      - "8546:8546"
#      - "30303:30303"
#      - "30303:30303/udp"
    volumes:
      - "~/.local/share/io.parity.ethereum/docker/:/root/.local/share/io.parity.ethereum/"
  ganache:
    image: trufflesuite/ganache-cli:v6.1.6
    # need -p because cli and gui have different default ports I think
    # need -h because of how docker networking works. Ganaches decides what host to listen to and docker-compose names
    # the network 'ganache' instead of 127.0.0.1
    command: ganache-cli -p 7545 -h ganache -m "nose foot asset wage radar canyon online bread hurry train absent bachelor"
#    command: ganache-cli --version
    ports:
      - "7545:7545"
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=loltesting
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  redis:
    image: redis:4
    ports:
      - "6379:6379"
    command: >
        redis-server --requirepass loltesting
  worker:
    environment:
      # can't use localhost because that always points to the current container. To talk to another container, it's
      # network name is the service name
      - CELERY_BROKER_URL=redis://:loltesting@redis:6379/0
      - DJANGO_DB_URL=postgres://user:loltesting@db:5432/postgres
      - GANACHE_ENDPOINT=http://ganache:7545
      # TODO figure out why these have to redeclared even though they exist in .env
      - DEPLOY_ENV=${DEPLOY_ENV}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PARITY_ENDPOINT=${PARITY_ENDPOINT}
    depends_on:
      - redis
      - db
      - ganache
      - server
      - parity
    build:
      context: .
      dockerfile: server.Dockerfile
      # TODO run the beat as a separate service instead of embedding in the worker
    command: celery -A backend worker -l info -B --scheduler django_celery_beat.schedulers:DatabaseScheduler
  server:
    depends_on:
      - redis
      - db
      - ganache
    environment:
      # can't use localhost because that always points to the current container. To talk to another container, it's
      # network name is the service name
      - CELERY_BROKER_URL=redis://:loltesting@redis:6379/0
      - DJANGO_DB_URL=postgres://user:loltesting@db:5432/postgres
      - DEPLOY_MYCRO_DAO=true
      - GANACHE_ENDPOINT=http://ganache:7545
      - PYTHONUNBUFFERED=1

      # TODO figure out why these have to redeclared even though they exist in .env
      - DEPLOY_ENV=${DEPLOY_ENV}
      - INFURA_API_KEY=${INFURA_API_KEY}
      - ETHEREUM_PRIVATE_KEY=${ETHEREUM_PRIVATE_KEY}
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8001:8000"
    # https://stackoverflow.com/questions/30063907/using-docker-compose-how-to-execute-multiple-commands
    command: >
      bash -c "./wait_for_it.sh db:5432  && ./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
#    volumes:
#      - '.:/mycro/backend'
  servertests:
    build:
      context: .
      dockerfile: server.Dockerfile
    command: >
      ./manage.py test
    volumes:
      - './backend:/mycro/backend'
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    depends_on:
      - ganache
    command: >
      bash -c "./wait_for_it.sh ganache:7545 && truffle migrate && npm start"
    ports:
      - "3000:3000"
    # volumes:
      # - './frontend:/mycro/'
