version: '2'

services:
  tests:
    build: 
      context: .
      dockerfile: tests.Dockerfile
    command: >
      watch -n 1 python3 -m unittest discover -v -s backend/tests
    volumes: 
      - '.:/mycro/backend'


