# Generated by Django 2.0.6 on 2018-06-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('github_access_token', models.CharField(max_length=40)),
                ('dao_address', models.CharField(max_length=40)),
            ],
        ),
    ]
