# Generated by Django 2.0.6 on 2018-10-22 15:34

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', encrypted_model_fields.fields.EncryptedCharField(unique=True)),
                ('address', models.CharField(max_length=42, unique=True)),
            ],
        ),
    ]
