# Generated by Django 2.0.6 on 2018-07-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='repo_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_access_token',
        ),
    ]
