# Generated by Django 2.0.6 on 2018-07-03 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_asc'),
        ('server', '0002_auto_20180703_0029'),
    ]

    operations = [
    ]
