# Generated by Django 2.0.6 on 2018-10-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=66, unique=True)),
                ('value', models.IntegerField()),
                ('chain_id', models.IntegerField()),
                ('nonce', models.IntegerField()),
                ('gas_limit', models.IntegerField()),
                ('gas_price', models.IntegerField()),
                ('data', models.TextField()),
                ('to', models.TextField()),
                ('block_number', models.IntegerField()),
                ('contract_address', models.CharField(max_length=44, unique=True)),
                ('cumulative_gas_used', models.IntegerField()),
                ('gas_used', models.IntegerField()),
                ('status', models.IntegerField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Wallet')),
            ],
        ),
    ]
