# Generated by Django 2.0.6 on 2018-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='chain_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
