# Generated by Django 2.0.6 on 2018-11-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='asc',
            name='blockchain_state',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'STARTED'), (2, 'COMPLETED'), (3, 'ERROR')], default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='blockchain_state',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'STARTED'), (2, 'COMPLETED'), (3, 'ERROR')], default=0),
        ),
    ]
