# Generated by Django 2.0 on 2018-07-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_merge_20180703_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asc',
            name='address',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='dao_address',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
