# Generated by Django 2.0.6 on 2018-07-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180709_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_mycro_dao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='last_merge_event_block',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='merge_module_address',
            field=models.CharField(max_length=42, unique=True),
            preserve_default=False,
        ),
    ]
