# Generated by Django 2.0.6 on 2018-11-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20181108_1617'),
        ('server', '0005_auto_20181110_2233'),
    ]

    operations = [
    ]
