# Generated by Django 2.0.6 on 2018-07-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20180709_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='merge_module_address',
            field=models.CharField(max_length=42),
        ),
    ]
