# Generated by Django 2.0.6 on 2018-11-13 15:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_merge_20181113_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='initial_balances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
