# Generated by Django 2.0.6 on 2018-08-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_asc_rewardee'),
    ]

    operations = [
        migrations.AddField(
            model_name='asc',
            name='reward',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
