# Generated by Django 2.0.6 on 2018-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_asc_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='asc',
            name='pr_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
