# Generated by Django 2.0.6 on 2018-09-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_asc_pr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='decimals',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='project',
            name='symbol',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
